name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    # Usa un runner self-hosted
    runs-on: self-hosted

    steps:
    # Verifica el repositorio de código
    - name: Checkout code
      uses: actions/checkout@v4

    # Usa Python 3.11 (ya disponible en tu máquina)
    - name: Use system Python 3.11
      run: python3 --version

    # Ejecuta tu script de Python
    - name: Run Python script
      run: python3 script.py
